spring:
  application:
    name: a11ymarket-server
  datasource:
    url: dbURL
    username: DBUSER
    password: DBPASSWORD
  jpa:
    show-sql: false
    properties.hibernate.show_sql: false
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: validate
  ai:
    model:
      chat: none # disable AI features because not implemented yet

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health # health check endpoint only

cors:
  allowed-origin-patterns:
    - "http://localhost:8080"
    - "http://localhost:5173"
    - # update with your domain