spring:
  application:
    name: a11ymarket-server
  # Database configuration
  datasource:
    url: dbURL
    username: DBUSER
    password: DBPASSWORD
  # JPA configuration
  jpa:
    show-sql: false
    properties.hibernate.show_sql: false
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: validate
  # Disable Open Session in View to prevent lazy loading issues
  open-in-view: false
  # AI model configuration
  ai:
    model:
      chat: none # disable AI features because not implemented yet

# Server configuration
server:
  port: 8080

# Management endpoint configuration
management:
  endpoints:
    web:
      exposure:
        include: health # health check endpoint only

# Logging configuration
logging:
  level:
    root: INFO
    com:
      multicampus:
        gamesungcoding:
          a11ymarketserver: DEBUG

# CORS configuration
cors:
  allowed-origin-patterns:
    - "http://localhost:8080"
    - "http://localhost:5173"
    - # update with your domain

    # JWT configuration
jwt:
  secret: your-jwt-secret-key
  access-token-validity-ms: 1800000
  refresh-token-validity-ms: 604800000

# Swagger configuration
springdoc:
  api-docs:
    enabled: true