spring:
  application:
    name: a11ymarket-server
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
  # Database configuration
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  # JPA configuration
  jpa:
    show-sql: ${JPA_SHOW_SQL:false}
    properties:
      hibernate:
        show_sql: ${JPA_SHOW_SQL:false}
        default_batch_fetch_size: 100
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:validate}
    # Disable Open Session in View to prevent lazy loading issues
    open-in-view: false
  # AI model configuration
  ai:
    openai:
      api-key: ${GEMINI_API_KEY}
      base-url: "https://generativelanguage.googleapis.com/v1beta/openai/"
      chat:
        options:
          model: "gemini-2.0-flash"
          temperature: 0.7
  # AWS S3 (or MinIO) configuration
  cloud:
    aws:
      region:
        static: ${S3_REGION:us-east-1}
      credentials:
        access-key: ${S3_ACCESS_KEY:user-access-key}
        secret-key: ${S3_SECRET_KEY:user-secret-key}
      s3:
        endpoint: ${S3_ENDPOINT_URL}
        path-style-access-enabled: true
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            client-name: Kakao
            redirect-uri: ${KAKAO_REDIRECT_URI:http://localhost:8080/login/oauth2/code/kakao}
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

oauth2:
  redirect-uri: ${OAUTH2_REDIRECT_URI:http://localhost:5173/auth/oauth-redirect}
  signup-uri: ${OAUTH2_SIGNUP_URI:http://localhost:5173/auth/oauth-signup}

# S3(MinIO) bucket configuration
app:
  s3:
    bucket: ${S3_BUCKET_NAME:a11ymarket-bucket}

# Server configuration
server:
  port: 8080

# Management endpoint configuration
management:
  endpoints:
    web:
      exposure:
        include: health # health check endpoint only

# Logging configuration
logging:
  level:
    root: ${LOGGING_LEVEL_ROOT:INFO}
    com:
      multicampus:
        gamesungcoding:
          a11ymarketserver: ${LOGGING_LEVEL_APP:INFO}

# CORS configuration
cors:
  allowed-origin-patterns: ${CORS_ALLOWED_ORIGINS:http://localhost:5173,http://locahost:8080}

  # JWT configuration
jwt:
  secret: ${JWT_SECRET}
  access-token-validity-ms: ${JWT_ACCESS_TOKEN_VALIDITY_MS:1800000}
  refresh-token-validity-ms: ${JWT_REFRESH_TOKEN_VALIDITY_MS:604800000}

toss:
  payment:
    secret-key: ${TOSS_PAYMENT_SECRET_KEY}

# Swagger configuration
springdoc:
  api-docs:
    enabled: ${SWAGGER_DOCS_ENABLED:true}
  swagger-ui:
    enabled: ${SWAGGER_UI_ENABLED:true}